### ISSUE TITLE
Question (points-to-tutorial15): Exception analysis rule typo?

### ISSUE THREAD

**Issue by csabahruska** [yanniss/yanniss.github.io#1]
Hello,

Thank you for writing the excellent points-to analysis tutorial (https://yanniss.github.io/points-to-tutorial15.pdf).
I'm reading the exception analysis chapter (3.2) and I do not understand the following rule from the figure 3.4:
![image](https://user-images.githubusercontent.com/877489/118268793-20ae1e80-b4be-11eb-98a4-b8ac01e00c64.png)

Why do the throw and catch refer to the same instruction in the method?
Is this a typo or do I miss something about how the IR is modelled?
IMO the throw and catch instructions should be two separate instructions in the same method.

**Comment by yanniss** [comment]
Thanks for the kind words. The meaning of the rule is that the method "throws" this abstract object if there is a `throw` instruction for the object in the method, without this instruction being covered by a `catch`. `Catch` is not a bytecode instruction, it's a range of code, so the "Catch" predicate does not map to a single instruction, it covers all instructions under it.

**Comment by csabahruska** [comment]
Ok, that makes sense. Thank you for the clarification.

**Comment by csabahruska** [comment]
On page 37 I believe that there is small typo:
![image](https://user-images.githubusercontent.com/877489/118295934-b8bb0080-b4dc-11eb-89d9-dcda7cadb3fa.png)
I assume the id2 function definition meant to be: `Object id2(Object a) { return id(a); }`

**Comment by yanniss** [comment]
Yes, that's right.
